SOCIAL_AUTH_USOSWEB_KEY = 'b8X4DBFft6YnSmbsJcKY'
SOCIAL_AUTH_USOSWEB_SECRET = 'yJqPH8hzEHBzTJKmLp25WLRVNKcqcuMUCkqQLcrJ'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGOUT_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_URL = '/login'
SOCIAL_AUTH_LOGOUT_URL = '/logout'